version: "3.7"
services:
  metabase:
    image: metabase/metabase:v0.41.5
    container_name: metabase
    restart: "always"
    environment:
      - JAVA_OPTS=-Xmx1g
      - MB_DB_TYPE=postgres
      - MB_DB_HOST=${DB_HOST_GLOBAL}
      - MB_DB_USER=${DB_USERNAME_GLOBAL}
      - MB_DB_PASS=${DB_PASSWORD_GLOBAL}
      - MB_DB_PORT=5432
      - MB_DB_DBNAME=metabase
    ports:
      - 3000:3000
  postgres:
    image: postgres:13.5-alpine
    container_name: metabase-postgres
    restart: unless-stopped
    ports:
      - 5432
    environment:
      - POSTGRES_DB=metabase
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  db-data:
    driver: local
