version: "3.7"
services:
  metabase:
    image: metabase/metabase:v0.40.1
    container_name: metabase
    restart: "always"
    environment:
      - JAVA_OPTS=-Xmx1g
      - MB_DB_TYPE=postgres
      - MB_DB_HOST=${DB_HOST}
      - MB_DB_USER=${DB_USERNAME}
      - MB_DB_PASS=${DB_PASSWORD}
      - MB_DB_PORT=5432
      - MB_DB_DBNAME=metabase
    ports:
      - 3000:3000
